AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: java8
    CodeUri: HelloWorldFunction
    Tracing: Active
    MemorySize: 512
  Api:
    # This removes the "Stage" stage automatically created
    # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api-properties
    OpenApiVersion: 3.0.1

Conditions:
  IsTrue: !Equals ["true", "true"]
  IsFalse: !Equals ["true", "false"]

Resources:
  MyStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  MyStreamNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: MyStreamName
      Value: !Ref MyStream

  StreamProducer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.StreamProducer::handleRequest
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref MyStreamNameParameter
        - KinesisCrudPolicy:
            StreamName: !Ref MyStream
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'

  StreamConsumer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.StreamConsumer::handleRequest
      Events:
        KinesisEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt MyStream.Arn
            StartingPosition: TRIM_HORIZON
            Enabled: true

  MyStringToJsonStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Create JSON string
        States:
          Create JSON string:
            Type: Pass
            Next: Parse to JSON
            Result:
              myJsonString:
                !If
                - IsTrue
                - '[\"is\", \"true\"]'
                - '[\"is\", \"false\"]'
          Parse to JSON:
            Type: Pass
            End: true
            InputPath: "$.myJsonString"
            Parameters:
              myJson.$: States.StringToJson($)
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
