AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: java8
    CodeUri: HelloWorldFunction

Resources:
  S3Putter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.S3Putter::handleRequest
      MemorySize: 512
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tracing: Active
      Environment:
        Variables:
          BUCKET_NAME: !Ref Bucket

  Bucket:
    Type: AWS::S3::Bucket
    Properties: {}
