AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Runtime: java8
    CodeUri: HelloWorldFunction
    Tracing: Active
    MemorySize: 512

Resources:
  S3Putter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.S3Putter::handleRequest
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Environment:
        Variables:
          BUCKET_NAME: !Ref MyBucket

  DdbPutter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.DdbPutter::handleRequest
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable

  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties: {}

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Put in S3
        States:
          Put in S3:
            Type: Task
            Resource: !GetAtt S3Putter.Arn
            Next: Put in Ddb
          Put in Ddb:
            Type: Task
            Resource: !GetAtt DdbPutter.Arn
            End: true
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess

  MyBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 360  # 6 * LambdaTimeout

  SenderToQueue:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.SenderToQueue::handleRequest
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue

  ReceiverFromQueue:
    Type: AWS::Serverless::Function
    Properties:
      Handler: me.jiashenb.trysam.ReceiverFromQueue::handleRequest
      Policies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Events:
        QueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
